name: Texter
main: Texter\Main
version: 1.6.5
api:
  - 2.0.0
  - 3.0.0
  - 4.0.0
  - 3.0.0-ALPHA5 #PocketMine-MP(api4.0/network)
author: fuyutsuki
website: https://twitter.com/y_fyi

permissions:
 texter.*:
  default: op
  description: "permission that allows player to use texter"
  children:
   texter.command.*:
    default: op
    description: "permission that allows player to use texter"
    children:
      texter.command.txt:
        default: op
        description: "permission that allows player to use texter"
